name = "plunk"
version = "1.2.2"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
description = "Library for interacting with Plunk's API (https://useplunk.com) in Gleam - supports both the Erlang and Javascript targets"
licences = ["MIT"]
repository = { type = "github", user = "aosasona", repo = "plunk.gleam" }
gleam = ">= 1.0.0"
# links = [{ title = "Website", href = "https://gleam.run" }]

internal_modules = ["plunk/internal/*"]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 1.0.0"
gleam_http = ">= 3.5.3 and < 4.0.0"
gleam_json = "1.0.1"                   # required for the conflicting gleam_json-OTP-27 upgrade

[dev-dependencies]
gleeunit = ">= 1.1.2 and < 2.0.0"
gleam_hackney = ">= 1.2.0 and < 2.0.0"
gleam_erlang = ">= 0.25.0 and < 1.0.0"
