name = "plunk"
version = "1.2.1"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
description = "Library for interacting with Plunk's API (https://useplunk.com) in Gleam - supports both the Erlang and Javascript targets"
licences = ["MIT"]
repository = { type = "github", user = "aosasona", repo = "plunk.gleam" }
gleam = ">= 0.33.0"
# links = [{ title = "Website", href = "https://gleam.run" }]

internal_modules = [
  "plunk/internal/*",
]

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"
gleam_http = "~> 3.5"
gleam_json = "~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"
gleam_hackney = "~> 1.2"
gleam_erlang = "~> 0.24"
